Raise minimum tested compiler to 1.70
Required by the most recent release of toml_edit.

    error: package `toml_edit v0.22.5` cannot be built because it requires rustc 1.70 or
    newer, while the currently active rustc version is 1.69.0
    Either upgrade to rustc 1.70 or newer, or use
    cargo update -p toml_edit@0.22.5 --precise ver
    where `ver` is the latest version of `toml_edit` supporting rustc 1.69.0