Raise minimum tested compiler to 1.69
Required by toml_edit.

    error: package `toml_edit v0.21.1` cannot be built because it requires rustc 1.69 or newer, while the currently active rustc version is 1.67.1
    Either upgrade to rustc 1.69 or newer, or use
    cargo update -p toml_edit@0.21.1 --precise ver
    where `ver` is the latest version of `toml_edit` supporting rustc 1.67.1