Raise minimum tested compiler to 1.67
Required by toml's dependency on serde_spanned.

    error: package `serde_spanned v0.6.4` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.66.0
    Either upgrade to rustc 1.67 or newer, or use
    cargo update -p serde_spanned@0.6.4 --precise ver
    where `ver` is the latest version of `serde_spanned` supporting rustc 1.66.0