Raise minimum tested compiler to 1.66
Required by toml_edit.

    error: package `toml_edit v0.19.15` cannot be built because it requires rustc 1.66.0 or newer, while the currently active rustc version is 1.65.0
    Either upgrade to rustc 1.66.0 or newer, or use
    cargo update -p toml_edit@0.19.15 --precise ver
    where `ver` is the latest version of `toml_edit` supporting rustc 1.65.0